### ISSUE TITLE
conda_auto_env.sh unable to find name and auto install

### ISSUE THREAD

**Issue by tallamjr** [ericmjl/dotfiles#1]
Hi @ericmjl ,

I came across your dotfiles repo/blog after watching one of your great talks on
youtube on Bayesian networks.

I really liked the conda environment hack you had in
http://www.ericmjl.com/blog/2018/12/25/conda-hacks-for-data-science-efficiency/

Of course I tried it out and it was great! There was two things that I've
added which might be of use to you so I thought I would put here as I didn't
know where best to write this (I thought opening a PR might be quite odd)

1. Sometimes I have projects which actually have comments in the headings of the
   `environment.yml` file which means the previous code was unable to find `"name: "` 
    easily. Therefore I found using `awk` to be a better alternative.

2. Occasionally I change directory into a project which
   contains an `environment.yml` file pertaining to a conda environment I do not
   have, but I do not actually want to install it. So, I have added a user input
   question to determine if they want to create an environment or not.

Please see the updated code below. Hopefully this is of some use to yourself,
but if not, no worries.

```
#!/bin/bash

function conda_auto_env() {
  if [ -e "environment.yml" ]; then
    # echo "environment.yml file found"
    # Get environment name associated with 'name' variable in file
    ENV=`grep 'name:' environment.yml | tail -n1 | awk '{ print $2}'`

    # Check if you are already in the environment
    if [[ $PATH != *$ENV* ]]; then
      # Check if the environment exists
      conda activate $ENV
      if [ $? -eq 0 ]; then
        :
      else
        # Create the environment and activate
        echo "Conda env '$ENV' doesn't exist."

        while true; do
            select choice in CREATE IGNORE
            do
                echo "$REPLY : $choice"
                break
            done

            case $choice in
                "CREATE" )
                    echo "Creating new conda environment from 'environment.yml' file found in folder..";
                    sleep 2;
                    conda env create -q;
                    conda activate $ENV;
                    break ;;
                "IGNORE" )
                    echo "Ceasing creating of new conda environment";
                    break ;;
                * )
                    echo "Please Choose Option 1, or 2" ;;
            esac
        done
      fi
    fi
  fi
}

export PROMPT_COMMAND=conda_auto_env
```

**Comment by ericmjl** [comment]
@tallamjr I'd totally welcome a PR for this! Would you like to do so? It'll ensure that your contribution is recorded on GitHub :smile:

**Comment by tallamjr** [comment]
Great, thanks! 

I have just made a PR now 🤓 I hope the changes in #2 come in handy.
